import {fetchOfficial,cameraFor} from './official.js';
import {getTelegramSnapshot} from './telegram.js';
const DESTS={2:{code:'PL',name:'Польща'},3:{code:'SK',name:'Словаччина'},4:{code:'HU',name:'Угорщина'},5:{code:'RO',name:'Румунія'}};
const COUNTRY_NAMES={PL:'Польща',SK:'Словаччина',HU:'Угорщина',RO:'Румунія',MD:'Молдова'};
const TTL=5*60*1000;
const OFFICIAL_TTL=2*60*1000;
const cache=new Map();
const officialCache=new Map();
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const s=v=>typeof v==='string'&&v.trim()?v.trim():null;
const pick=(o,ks)=>{for(const k of ks)if(o?.[k]!=null)return o[k];return null};
const tr=v=>{v=String(v??'').toLowerCase();if(['up','rising','increase','increasing','↑'].includes(v))return'up';if(['down','falling','decrease','decreasing','↓'].includes(v))return'down';if(['flat','stable','same','→'].includes(v))return'flat';return'unknown'};
const keyName=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[–—-]/g,' ').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function rowsFrom(body){if(Array.isArray(body?.data))return body.data;if(Array.isArray(body?.data?.checkpoints))return body.data.checkpoints;if(Array.isArray(body?.checkpoints))return body.checkpoints;return[]}
function conf(row,age){const q=String(pick(row,['data_quality','quality'])||'').toLowerCase();if(q==='high'&&(age==null||age<=30))return'high';if(q==='low')return'low';if(age!=null&&age<=20)return'high';if(age!=null&&age<=60)return'medium';return'low'}
function norm(row,originId,destId){const c=DESTS[destId]||{code:String(destId),name:String(destId)};const ppid=s(pick(row,['ppid','id','checkpoint_id']));const name=s(pick(row,['name','checkpoint_name','title','crossing_name']))||ppid||'Невідомий КПП';const queueCars=n(pick(row,['queue','queue_now','cars','vehicles']));const waitMin=n(pick(row,['wait_min','wait_minutes','estimated_wait_min','waiting_time_min']));const ageMin=n(pick(row,['age_min','age_minutes','data_age_min']));const updatedAt=s(pick(row,['updated_at','timestamp','as_of','last_update']));const stale=typeof row?.stale==='boolean'?row.stale:(ageMin!=null?ageMin>60:false);const direction=originId===1?'UA_EU':'EU_UA';const sourceUrl=s(pick(row,['source_url','url']));return{id:`${ppid||name}-${direction}`,ppid,name,country:c.name,countryCode:c.code,direction,queueCars,waitMin,waitStatus:s(pick(row,['wait_status','status'])),ageMin,updatedAt,trend:tr(pick(row,['trend_direction','trend','trend_status'])),trendPercent:n(pick(row,['trend_percent'])),stale,confidence:conf(row,ageMin),sourceUrl,sources:[{source:'nakordoni',label:'Nakordoni',value:waitMin,updatedAt,ageMin,sourceUrl,note:queueCars!=null?`${queueCars} авто`:null}]}}
async function fetchJson(url,key){const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),20000);try{const r=await fetch(url,{headers:{Authorization:`Bearer ${key}`,Accept:'application/json'},signal:ctl.signal,cache:'no-store'});const body=await r.json().catch(()=>null);return{ok:r.ok&&body?.ok!==false,status:r.status,body}}finally{clearTimeout(t)}}
async function getNkd(key,direction){const reqs=Object.keys(DESTS).map(Number).map(destId=>{const originId=direction==='UA_EU'?1:destId;const destinationId=direction==='UA_EU'?destId:1;return{destId,originId,destinationId,url:`https://nakordoni.eu/api/v4/data/border/${originId}/${destinationId}/4?lang=uk`}});const out=await Promise.all(reqs.map(async(q,i)=>{if(i)await sleep(i*600);try{return{...q,...await fetchJson(q.url,key)}}catch(e){return{...q,ok:false,status:0,error:String(e),body:null}}}));const crossings=[],failures=[],usage=[];let attribution='Data by nakordoni.eu';for(const r of out){if(!r.ok){failures.push({countryCode:DESTS[r.destId]?.code,httpStatus:r.status,error:r.body?.error?.message||r.body?.error||r.error||'upstream_error'});continue}if(r.body?.usage)usage.push(r.body.usage);if(r.body?.attribution)attribution=r.body.attribution;for(const row of rowsFrom(r.body)){const x=norm(row,r.originId,r.destId);if(x)crossings.push(x)}}return{crossings,failures,usage,attribution}}
async function getOfficial(direction){let x=officialCache.get(direction);if(!x||Date.now()-x.ts>OFFICIAL_TTL){x={ts:Date.now(),value:await fetchOfficial(direction)};officialCache.set(direction,x)}return x.value}
async function getTelegram(){try{const b=await getTelegramSnapshot();const src=Array.isArray(b?.sources)?b.sources:[];const connected=src.filter(x=>x.status==='connected').length;const status=connected===0?'error':connected===src.length?'connected':'partial';return{status,items:Array.isArray(b?.items)?b.items:[],sources:src}}catch(e){return{status:'error',items:[],sources:[],error:String(e?.message||e)}}}
function mergeOfficial(crossings,items,direction){const out=crossings.map(x=>({...x,sources:[...(x.sources||[])]}));for(const e of items||[]){if(e.direction!==direction)continue;let f=out.find(x=>x.countryCode===e.countryCode&&e.aliases?.some(a=>keyName(`${x.name} ${(x.sources||[]).map(z=>z.note||'').join(' ')}`).includes(keyName(a))));if(!f){f={id:`official-${e.countryCode}-${keyName(e.note||e.aliases?.[0]||'crossing')}-${direction}`,ppid:null,name:(e.note||e.aliases?.[0]||'Офіційний КПП').split(' · ')[0],country:COUNTRY_NAMES[e.countryCode]||e.countryCode,countryCode:e.countryCode,direction,queueCars:null,waitMin:e.waitMin,waitStatus:null,ageMin:e.ageMin??null,updatedAt:e.updatedAt||null,trend:'unknown',trendPercent:null,stale:false,confidence:'high',sourceUrl:e.sourceUrl||null,sources:[]};out.push(f)}const src={...e};delete src.aliases;f.sources.push(src);if(f.waitMin==null&&e.waitMin!=null)f.waitMin=e.waitMin;if(!f.updatedAt&&e.updatedAt)f.updatedAt=e.updatedAt;if(f.ageMin==null&&e.ageMin!=null)f.ageMin=e.ageMin;if(e.waitMin!=null)f.confidence='high'}return out.map(x=>({...x,camera:cameraFor(x)}))}
function rowMatches(x,name,countryCode,aliases=[]){if(countryCode&&x.countryCode&&x.countryCode!==countryCode)return false;const a=keyName(x.name),b=keyName(name);if(a&&b&&(a.includes(b)||b.includes(a)))return true;const rowText=keyName(`${x.name} ${(x.sources||[]).map(z=>z.note||'').join(' ')}`);return aliases.some(v=>{const k=keyName(v);return k&&rowText.includes(k)})}
function chatMeta(src){return{label:src.label||src.checkpoint||src.channel,channel:src.channel||null,url:src.channelUrl||null,status:src.status||'unknown',freshReports:src.items??0}}
function mergeTelegram(crossings,items,direction,chatSources=[]){const out=crossings.map(x=>({...x,sources:[...(x.sources||[])],humanReports:x.humanReports||0,humanSignal:x.humanSignal||null}));
  for(const chat of Array.isArray(chatSources)?chatSources:[]){if(chat.kind!=='checkpoint_chat'||!chat.checkpoint)continue;const f=out.find(x=>rowMatches(x,chat.checkpoint,chat.countryCode,chat.aliases||[]));if(f)f.telegramChat=chatMeta(chat)}
  for(const raw of Array.isArray(items)?items:[]){const name=s(pick(raw,['checkpoint','name','crossing']));if(!name)continue;const dir=String(raw.direction||'').toUpperCase().startsWith('EU')?'EU_UA':'UA_EU';if(dir!==direction)continue;const countryCode=s(raw.country_code||raw.countryCode)||'';const aliases=[];let f=out.find(x=>rowMatches(x,name,countryCode,aliases));const rawWait=pick(raw,['wait_min','waitMinutes','waiting_time_min']);const waitMin=rawWait==null?null:n(rawWait);const rawAge=pick(raw,['age_min','ageMinutes']);const ageMin=rawAge==null?null:n(rawAge);const rawQueue=pick(raw,['queue_cars','cars','queue']);const queueCars=rawQueue==null?null:n(rawQueue);const updatedAt=s(pick(raw,['updated_at','timestamp','as_of']));const note=s(pick(raw,['note','text','summary']));const sourceUrl=s(raw.source_url||raw.sourceUrl);const sourceLabel=s(raw.source_label||raw.sourceLabel)||'Telegram';const channelUrl=s(raw.channel_url||raw.channelUrl);const sourceChannel=s(raw.source_channel||raw.sourceChannel);const replyContext=s(raw.reply_context||raw.replyContext);const directionBasis=s(raw.direction_basis||raw.directionBasis);if(!f){f={id:`tg-${keyName(name)}-${dir}`,name,country:s(raw.country)||COUNTRY_NAMES[countryCode]||'',countryCode,direction:dir,queueCars:null,waitMin:null,ageMin:null,updatedAt:null,trend:'unknown',trendPercent:null,stale:false,confidence:'low',sourceUrl:null,sources:[],humanReports:0,humanSignal:'reported'};out.push(f)}f.sources.push({source:'telegram',label:sourceLabel,value:waitMin,queueCars,updatedAt,ageMin,note:note||(queueCars!=null?`${queueCars} авто`:null),replyContext,directionBasis,sourceUrl,channelUrl,sourceChannel});if(channelUrl)f.telegramChat={label:sourceLabel,channel:sourceChannel,url:channelUrl,status:'connected',freshReports:(f.telegramChat?.freshReports||0)+1};f.humanReports=(f.humanReports||0)+1;f.humanSignal=f.humanReports>=2?'corroborated':'reported'}return out.map(x=>({...x,camera:x.camera||cameraFor(x)}))}
function sort(rows){return[...rows].sort((a,b)=>(a.stale?1:0)-(b.stale?1:0)||(a.waitMin??999999)-(b.waitMin??999999)||(a.ageMin??9999)-(b.ageMin??9999))}
async function fetchRegionalUpstream(direction){const base=process.env.UPSTREAM_AGGREGATOR_URL?.replace(/\/$/,'');if(!base)return null;try{const r=await fetch(`${base}/api/aggregate?direction=${direction}`,{headers:{Accept:'application/json'},cache:'no-store'});const body=await r.json().catch(()=>null);if(!r.ok||!body?.ok)return null;return body}catch{return null}}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({ok:false,error:'method_not_allowed'});const direction=req.query?.direction==='EU_UA'?'EU_UA':'UA_EU';const regional=await fetchRegionalUpstream(direction);if(regional)return res.status(200).json({...regional,viaRegionalUpstream:true});const generatedAt=new Date().toISOString();const [tg,official]=await Promise.all([getTelegram(),getOfficial(direction)]);const apiKey=process.env.NKD_API_KEY||s(req.headers?.['x-nkd-key']);if(!apiKey){const rows=mergeTelegram(mergeOfficial([],official.items,direction),tg.items,direction,tg.sources);return res.status(200).json({ok:true,generatedAt,direction,apiVersion:'v4',cacheMinutes:5,crossings:sort(rows),sourceStatus:{nakordoni:'missing_key',official:official.status,cameras:'configured',telegram:tg.status},attribution:'Data by nakordoni.eu'})}const ck=`${apiKey.slice(-6)}:${direction}`;let nkd=cache.get(ck);let fromCache=true;if(!nkd||Date.now()-nkd.ts>TTL){nkd={ts:Date.now(),value:await getNkd(apiKey,direction)};cache.set(ck,nkd);fromCache=false}const x=nkd.value;let rows=mergeOfficial(x.crossings,official.items,direction);rows=mergeTelegram(rows,tg.items,direction,tg.sources);return res.status(200).json({ok:true,generatedAt,direction,apiVersion:'v4',cacheMinutes:5,fromCache,crossings:sort(rows),sourceStatus:{nakordoni:x.crossings.length?'connected':(x.failures.length?'error':'empty'),official:official.status,cameras:'configured',telegram:tg.status},attribution:x.attribution,usage:x.usage,failures:x.failures})}
