const CACHE_TTL=2*60*1000;
const DIR_TTL=60*60*1000;
const trafficCache=new Map();
let directoryCache={ts:0,items:[]};
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
function coordsOf(x){const c=x?.coordinates||x?.coordinate||x?.coords||{};return{lat:n(x?.lat??x?.latitude??c?.lat??c?.latitude),lon:n(x?.lon??x?.lng??x?.longitude??c?.lon??c?.lng??c?.longitude)}}
async function fetchJson(url,headers={},timeout=15000){const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{headers:{Accept:'application/json',...headers},signal:ctl.signal,cache:'no-store'});const body=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,body}}finally{clearTimeout(t)}}
async function directory(apiKey){if(Date.now()-directoryCache.ts<DIR_TTL&&directoryCache.items.length)return directoryCache.items;const r=await fetchJson('https://nakordoni.eu/api/v1/data/checkpoints?lang=uk',{Authorization:`Bearer ${apiKey}`},20000);if(!r.ok||r.body?.ok===false)throw new Error(r.body?.error?.message||`Nakordoni ${r.status}`);const items=r.body?.data?.checkpoints||r.body?.data?.items||r.body?.data||[];directoryCache={ts:Date.now(),items:Array.isArray(items)?items:[]};return directoryCache.items}
function summarizeFlow(body){const results=Array.isArray(body?.results)?body.results:[];const rows=results.map(x=>({jamFactor:n(x?.currentFlow?.jamFactor),speed:n(x?.currentFlow?.speed),freeFlow:n(x?.currentFlow?.freeFlow),confidence:n(x?.currentFlow?.confidence),length:n(x?.location?.length)})).filter(x=>x.jamFactor!=null||x.speed!=null);if(!rows.length)return null;const jams=rows.map(x=>x.jamFactor).filter(x=>x!=null);const speeds=rows.map(x=>x.speed).filter(x=>x!=null).sort((a,b)=>a-b);const maxJam=jams.length?Math.max(...jams):null;const avgJam=jams.length?jams.reduce((a,b)=>a+b,0)/jams.length:null;const medianSpeed=speeds.length?speeds[Math.floor(speeds.length/2)]:null;let level='unknown';if(maxJam!=null)level=maxJam>=8?'severe':maxJam>=5?'heavy':maxJam>=2.5?'moderate':'light';return{level,jamFactorMax:maxJam==null?null:Math.round(maxJam*10)/10,jamFactorAvg:avgJam==null?null:Math.round(avgJam*10)/10,speedKmh:medianSpeed==null?null:Math.round(medianSpeed),segments:rows.length,sourceUpdated:body?.sourceUpdated||null}}
async function localTraffic(ppid){const hereKey=process.env.HERE_API_KEY;const nkdKey=process.env.NKD_API_KEY;if(!hereKey)return{status:503,body:{ok:false,error:'missing_here_key'}};if(!nkdKey)return{status:503,body:{ok:false,error:'missing_nakordoni_key'}};const cached=trafficCache.get(ppid);if(cached&&Date.now()-cached.ts<CACHE_TTL)return{status:200,body:{...cached.body,fromCache:true}};const items=await directory(nkdKey);const row=items.find(x=>String(x?.ppid)===String(ppid));if(!row)return{status:404,body:{ok:false,error:'checkpoint_not_found'}};const {lat,lon}=coordsOf(row);if(lat==null||lon==null)return{status:422,body:{ok:false,error:'checkpoint_coordinates_missing'}};const qs=new URLSearchParams({in:`circle:${lat},${lon};r=3000`,locationReferencing:'shape',apiKey:hereKey});const r=await fetchJson(`https://data.traffic.hereapi.com/v7/flow?${qs.toString()}`,{},15000);if(!r.ok)return{status:r.status===401||r.status===403?502:r.status,body:{ok:false,error:'here_upstream_error',upstreamStatus:r.status}};const summary=summarizeFlow(r.body);const body={ok:true,ppid,lat,lon,radiusM:3000,traffic:summary,provider:'HERE Traffic API v7',generatedAt:new Date().toISOString()};trafficCache.set(ppid,{ts:Date.now(),body});return{status:200,body}}
async function regional(ppid){const base=process.env.UPSTREAM_AGGREGATOR_URL?.replace(/\/$/,'');if(!base)return null;try{const r=await fetch(`${base}/api/traffic?ppid=${encodeURIComponent(ppid)}`,{headers:{Accept:'application/json'},cache:'no-store'});const b=await r.json().catch(()=>null);if(r.ok&&b?.ok)return{status:200,body:{...b,viaRegionalUpstream:true}};if(b?.error==='missing_here_key')return{status:r.status,body:b};return null}catch{return null}}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({ok:false,error:'method_not_allowed'});const ppid=String(req.query?.ppid||'').trim();if(!ppid)return res.status(400).json({ok:false,error:'missing_ppid'});const up=await regional(ppid);if(up)return res.status(up.status).json(up.body);try{const out=await localTraffic(ppid);return res.status(out.status).json(out.body)}catch(e){return res.status(502).json({ok:false,error:'traffic_failed',message:String(e?.message||e)})}}
